# Generated by Django 4.1 on 2023-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nbloggedin',
            field=models.IntegerField(default=0),
        ),
    ]
